# Generated by Django 5.2.8 on 2026-03-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_perfilpaciente_ciudad_residencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpaciente',
            name='anios_estudio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Años de escolarización'),
        ),
    ]
