# Generated by Django 5.2.8 on 2026-03-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_perfilpaciente_anios_estudio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilpaciente',
            name='puntuacion_cognitiva',
        ),
        migrations.RemoveField(
            model_name='perfilpaciente',
            name='puntuacion_motora',
        ),
    ]
