# Generated by Django 5.2.8 on 2026-03-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_perfilpaciente_puntuacion_cognitiva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionmoca',
            name='revisada_por_medico',
            field=models.BooleanField(default=False, verbose_name='Revisada por el Médico'),
        ),
    ]
