# Generated by Django 5.2.8 on 2026-03-23 13:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_evaluacionmoca_revisada_por_medico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionBuzon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.CharField(choices=[('SISTEMA', 'Sistema SamiraDTx'), ('MEDICO', 'Especialista Médico')], default='SISTEMA', max_length=20)),
                ('mensaje', models.TextField(verbose_name='Contenido del mensaje')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('leida', models.BooleanField(default=False)),
                ('medico_autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.perfilpaciente')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
