# Generated by Django 5.2.8 on 2026-03-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_notificacionbuzon'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionmoca',
            name='abstraccion_reloj_score',
            field=models.IntegerField(default=0, verbose_name='Abstracción: Reloj/Regla'),
        ),
        migrations.AddField(
            model_name='evaluacionmoca',
            name='abstraccion_tren_score',
            field=models.IntegerField(default=0, verbose_name='Abstracción: Tren/Bici'),
        ),
        migrations.AddField(
            model_name='evaluacionmoca',
            name='atencion_letras_errores',
            field=models.IntegerField(default=0, verbose_name='Atención: Errores en Letras'),
        ),
        migrations.AddField(
            model_name='evaluacionmoca',
            name='atencion_letras_score',
            field=models.IntegerField(default=0, verbose_name='Atención: Nota Letras (0-1)'),
        ),
        migrations.AddField(
            model_name='evaluacionmoca',
            name='atencion_numeros_dir',
            field=models.IntegerField(default=0, verbose_name='Atención: Números Directos'),
        ),
        migrations.AddField(
            model_name='evaluacionmoca',
            name='atencion_numeros_inv',
            field=models.IntegerField(default=0, verbose_name='Atención: Números Inversos'),
        ),
        migrations.AddField(
            model_name='evaluacionmoca',
            name='atencion_restas_score',
            field=models.IntegerField(default=0, verbose_name='Atención: Restas de 7 (0-3)'),
        ),
        migrations.AddField(
            model_name='evaluacionmoca',
            name='lenguaje_fluidez_score',
            field=models.IntegerField(default=0, verbose_name='Lenguaje: Fluidez Verbal'),
        ),
        migrations.AddField(
            model_name='evaluacionmoca',
            name='lenguaje_rep_1',
            field=models.IntegerField(default=0, verbose_name='Lenguaje: Repetición Frase 1'),
        ),
        migrations.AddField(
            model_name='evaluacionmoca',
            name='lenguaje_rep_2',
            field=models.IntegerField(default=0, verbose_name='Lenguaje: Repetición Frase 2'),
        ),
        migrations.AddField(
            model_name='evaluacionmoca',
            name='memoria_intento1',
            field=models.IntegerField(default=0, verbose_name='Memoria: Intento 1 (0-5)'),
        ),
        migrations.AddField(
            model_name='evaluacionmoca',
            name='memoria_intento2',
            field=models.IntegerField(default=0, verbose_name='Memoria: Intento 2 (0-5)'),
        ),
        migrations.AddField(
            model_name='evaluacionmoca',
            name='orientacion_anio',
            field=models.IntegerField(default=0, verbose_name='Orientación: Año'),
        ),
        migrations.AddField(
            model_name='evaluacionmoca',
            name='orientacion_dia_mes',
            field=models.IntegerField(default=0, verbose_name='Orientación: Día Mes'),
        ),
        migrations.AddField(
            model_name='evaluacionmoca',
            name='orientacion_dia_semana',
            field=models.IntegerField(default=0, verbose_name='Orientación: Día Semana'),
        ),
        migrations.AddField(
            model_name='evaluacionmoca',
            name='orientacion_localidad',
            field=models.IntegerField(default=0, verbose_name='Orientación: Localidad'),
        ),
        migrations.AddField(
            model_name='evaluacionmoca',
            name='orientacion_lugar',
            field=models.IntegerField(default=0, verbose_name='Orientación: Lugar'),
        ),
        migrations.AddField(
            model_name='evaluacionmoca',
            name='orientacion_mes',
            field=models.IntegerField(default=0, verbose_name='Orientación: Mes'),
        ),
        migrations.AddField(
            model_name='evaluacionmoca',
            name='respuesta_animal_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Animal 1'),
        ),
        migrations.AddField(
            model_name='evaluacionmoca',
            name='respuesta_animal_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Animal 2'),
        ),
        migrations.AddField(
            model_name='evaluacionmoca',
            name='respuesta_animal_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Animal 3'),
        ),
        migrations.AddField(
            model_name='evaluacionmoca',
            name='score_tmt',
            field=models.IntegerField(default=0, verbose_name='Visoespacial: TMT'),
        ),
    ]
